language: python

sudo: false

addons:
  apt:
    packages:
      - help2man

env:
  matrix:
    - VLUA="lua=5.4"
    - VLUA="lua=5.3"
    - VLUA="lua=5.2"
    - VLUA="lua=5.1"
    - VLUA="luajit=2.1"
    - VLUA="luajit=2.0"

before_install:
  - pip install hererocks
  - hererocks here --luarocks 3 --$VLUA
  - export PATH=$PWD/here/bin:$PATH

  - hererocks tools --luajit=2.0
  - export PATH=$PATH:$PWD/tools/bin

install:
  - luarocks --lua-dir=$PWD/tools --tree=$PWD/tools install luacov

script:
  - make all
  - luarocks make
  - make check SPECL_OPTS='-vfreport --coverage'

after_success:
  - bash <(curl -s https://codecov.io/bash) -f luacov.report.out

notifications:
  slack: aspirinc:JyWeNrIdS0J5nf2Pn2BS1cih
