owner:   Gary V. Vaughan
account: gvvaughan

name:         Specl
description:  Behaviour Driven Development for Lua.
forkme:       "https://github.com/gvvaughan/specl"
release-no:   14.1.4

url:      "http://gvvaughan.github.io/specl"
markdown: kramdown
pygments: true
