name: spec

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        lua-version: ["5.4", "5.3", "5.2", "5.1", "luajit"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.lua-version }}

      - uses: leafo/gh-actions-luarocks@v4
        with:
          luaRocksVersion: 3.9.2

      - name: install
        run: |
          sudo apt-get install -y help2man
          sudo apt-get install -y libyaml-dev
          luarocks install ansicolors
          luarocks install ldoc
          luarocks install luacov
          luarocks install specl

      - name: build
        run: |
          luarocks make --force

      - name: test
        run: |
          specl -vfreport --coverage spec/*_spec.yaml
          bash <(curl -s https://codecov.io/bash) -f luacov.report.out
